// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6nba_JT6IXlvsO4Omp5Htoyk02YdGPo',
    appId: '1:1050289220442:web:0910f453e230c796e42163',
    messagingSenderId: '1050289220442',
    projectId: 'flutter-crud-7206a',
    authDomain: 'flutter-crud-7206a.firebaseapp.com',
    storageBucket: 'flutter-crud-7206a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDou-9CN9iuSjWBuWjwjHZUnAz_pyWXRzQ',
    appId: '1:1050289220442:android:c6fccb3f094ffa6de42163',
    messagingSenderId: '1050289220442',
    projectId: 'flutter-crud-7206a',
    storageBucket: 'flutter-crud-7206a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFSc3EkDk77_sNq-NUpFTuevhbftFdXDE',
    appId: '1:1050289220442:ios:456e56c12f22f90be42163',
    messagingSenderId: '1050289220442',
    projectId: 'flutter-crud-7206a',
    storageBucket: 'flutter-crud-7206a.appspot.com',
    iosClientId: '1050289220442-hsffv210o5cgkr2b0hht2qg9jdd3pf5d.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividadFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFSc3EkDk77_sNq-NUpFTuevhbftFdXDE',
    appId: '1:1050289220442:ios:ea13b22d9503e775e42163',
    messagingSenderId: '1050289220442',
    projectId: 'flutter-crud-7206a',
    storageBucket: 'flutter-crud-7206a.appspot.com',
    iosClientId: '1050289220442-3dqkgbvvqvfmso8dv0uj263i5vcdo6s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividadFinal.RunnerTests',
  );
}
